export const theme = {
  colors: {
    background: '#FFF8F1',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    textPrimary: '#1F2937',
    textSecondary: '#4B5563',
    textMuted: '#6B7280',
    border: '#F1D8BE',
    primary: '#F97316',
    primarySoft: '#FDBA74',
    primaryContrast: '#FFFFFF',
    success: '#166534',
    warning: '#B45309',
    danger: '#B91C1C',
    info: '#EA580C',
    chipBg: '#FFF1E6',
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 18,
    full: 999,
  },
  typography: {
    h1: { fontSize: 28, fontWeight: '700' as const },
    h2: { fontSize: 22, fontWeight: '700' as const },
    h3: { fontSize: 18, fontWeight: '600' as const },
    body: { fontSize: 15, fontWeight: '400' as const },
    bodyStrong: { fontSize: 15, fontWeight: '600' as const },
    caption: { fontSize: 12, fontWeight: '500' as const },
  },
  shadow: {
    card: {
      shadowColor: '#C2410C',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 14,
      elevation: 3,
    },
  },
};
