export const theme = {
  colors: {
    background: '#F4F7FB',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    textPrimary: '#1E3248',
    textSecondary: '#4B647C',
    textMuted: '#7A8FA3',
    border: '#DAE4EF',
    primary: '#2E7D32',
    primarySoft: '#A5D6A7',
    primaryContrast: '#FFFFFF',
    success: '#1E7A4B',
    warning: '#B7791F',
    danger: '#C53030',
    info: '#2F855A',
    chipBg: '#EAF6EE',
    accentDark: '#16324A',
  },
  spacing: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 28,
    xxl: 36,
  },
  radius: {
    sm: 12,
    md: 16,
    lg: 20,
    full: 999,
  },
  typography: {
    h1: { fontSize: 38, fontWeight: '700' as const, fontFamily: 'Poppins-Regular' },
    h2: { fontSize: 22, fontWeight: '700' as const, fontFamily: 'Poppins-Regular' },
    h3: { fontSize: 17, fontWeight: '600' as const, fontFamily: 'Poppins-Regular' },
    body: { fontSize: 13, fontWeight: '400' as const, fontFamily: 'Poppins-Regular' },
    bodyStrong: { fontSize: 13, fontWeight: '600' as const, fontFamily: 'Poppins-Regular' },
    caption: { fontSize: 10, fontWeight: '500' as const, fontFamily: 'Poppins-Regular' },
  },
  shadow: {
    card: {
      shadowColor: '#1E3248',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 16,
      elevation: 3,
    },
    soft: {
      shadowColor: '#1E3248',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 1,
    },
  },
};
